logging:
  level:
    org.hibernate.SQL: DEBUG
    com.data.warehouse: DEBUG

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
    hibernate:
      ddl-auto: update
    hikari:
      poolName: Hikari
      auto-commit: false
#  security:
#    jwt:
#      secret: ThisIsArEALLYlONGsECRETtHATNOoNEcANaCTUALLYgueSs.tRyItIfYoUcAN
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days